// <auto-generated />
using System;
using MITCRMS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MITCRMS.Migrations
{
    [DbContext(typeof(MitcrmsContext))]
    [Migration("20260125210606_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MITCRMS.Models.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Bursar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Bursars");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("HodId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("HodId")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Hod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Hods");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("BursarId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HodId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tittle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("BursarId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("HodId");

                    b.HasIndex("TutorId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("a45c9e02-1f0b-4e57-b3d8-9b77b4a302be"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Hod"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a871"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Bursar"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a882"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("6e3d4978-dcb0-42ea-9c48-7f6209d4a856"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Tutor"
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.SuperAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SuperAdmins");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0e25b73-7d1a-4c19-8b2f-09a3efb40d12"),
                            Address = "Ogun State",
                            DateCreated = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "SuperAdmin",
                            LastName = "Mitcrms",
                            PhoneNumber = "+23470456780",
                            UserId = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e42")
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BursarId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("HodId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("SuperAdminId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e42"),
                            AdminId = new Guid("00000000-0000-0000-0000-000000000000"),
                            BursarId = new Guid("00000000-0000-0000-0000-000000000000"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Admin001@gmail.com",
                            EmailConfirmed = true,
                            HodId = new Guid("00000000-0000-0000-0000-000000000000"),
                            PasswordHash = "AQAAAAIAAYagAAAAEJjieFsJGM2Xgr+WpuS3juOABbBCvbqSvpym4WzP/SDMuvGz6qH+EFgm19l8SUHUGA==",
                            SuperAdminId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TutorId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ad9b1e1-4c23-46a2-b8e4-219ab417f71f"),
                            DateCreated = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc"),
                            UserId = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e42")
                        });
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Admin", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Department", "Department")
                        .WithMany("Admins")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("MITCRMS.Models.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Bursar", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Department", "Department")
                        .WithMany("Bursars")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithOne("Bursar")
                        .HasForeignKey("MITCRMS.Models.Entities.Bursar", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Department", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Hod", "Hod")
                        .WithOne("Department")
                        .HasForeignKey("MITCRMS.Models.Entities.Department", "HodId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Hod");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Hod", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Department", null)
                        .WithMany("Hods")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithOne("Hod")
                        .HasForeignKey("MITCRMS.Models.Entities.Hod", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Report", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Admin", "Admin")
                        .WithMany("Reports")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.Bursar", "Bursar")
                        .WithMany("Reports")
                        .HasForeignKey("BursarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.Department", "Department")
                        .WithMany("Reports")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.Hod", "Hod")
                        .WithMany("Reports")
                        .HasForeignKey("HodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.Tutor", "Tutor")
                        .WithMany("Reports")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Bursar");

                    b.Navigation("Department");

                    b.Navigation("Hod");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.SuperAdmin", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithOne("SuperAdmin")
                        .HasForeignKey("MITCRMS.Models.Entities.SuperAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Tutor", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Department", "Department")
                        .WithMany("Tutors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithOne("Tutor")
                        .HasForeignKey("MITCRMS.Models.Entities.Tutor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.UserRole", b =>
                {
                    b.HasOne("MITCRMS.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MITCRMS.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Admin", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Bursar", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Department", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Bursars");

                    b.Navigation("Hods");

                    b.Navigation("Reports");

                    b.Navigation("Tutors");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Hod", b =>
                {
                    b.Navigation("Department")
                        .IsRequired();

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.Tutor", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MITCRMS.Models.Entities.User", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Bursar")
                        .IsRequired();

                    b.Navigation("Hod")
                        .IsRequired();

                    b.Navigation("SuperAdmin")
                        .IsRequired();

                    b.Navigation("Tutor")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
